# Generated by Django 3.2.9 on 2021-11-06 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModelMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=254, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=254, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('sex', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=254, verbose_name='Sex')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('employment_date', models.DateField(auto_now_add=True, verbose_name='Employment date')),
                ('termination_date', models.DateField(default=datetime.datetime(2024, 11, 5, 6, 51, 28, 41531, tzinfo=utc), verbose_name='Termination date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('', ''), ('Moderna', 'Moderna'), ('Novarax', 'Novarax'), ('Oxford AstraZeneca', 'Oxford AstraZeneca'), ('Pfizer-BioNTech', 'Pfizer-BioNTech'), ('Sinopharm', 'Sinopharm'), ('Sinovac', 'Sinovac'), ('Sputnik V', 'Sputnik V')], max_length=254, verbose_name='Brand')),
                ('first_dose_date', models.DateField(verbose_name='Date of 1st dose')),
                ('second_dose_date', models.DateField(blank=True, null=True, verbose_name='Date of 2nd dose')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='Status')),
                ('vaccine_card_id', models.FileField(upload_to='vaccine_id/', verbose_name='Photo of vaccine card')),
                ('personal_info', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_info', to='mainapp.genericmodelmain', verbose_name='Personal Identifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=254, verbose_name='Sex')),
                ('phone', models.CharField(max_length=254, verbose_name='Phone number')),
                ('address_full', models.CharField(max_length=1000, verbose_name='Full address')),
                ('address_barangay', models.CharField(max_length=1000, verbose_name='Barangay')),
                ('address_city', models.CharField(max_length=1000, verbose_name='City/Municipality')),
                ('address_province', models.CharField(max_length=1000, verbose_name='Province')),
                ('address_zip', models.CharField(max_length=4, verbose_name='Zip code')),
                ('government_id', models.FileField(upload_to='people_id/', verbose_name='Photo of government-issued ID')),
                ('role', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericModelForeign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_cadet', models.ManyToManyField(default='', related_name='engine_cadet', to='mainapp.GenericModelMain', verbose_name='Engine cadet')),
                ('second_engineer', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_engineer', to='mainapp.genericmodelmain', verbose_name='Second engineer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstablishmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name of establishment')),
                ('address_full', models.CharField(max_length=1000, verbose_name='Full address')),
                ('address_barangay', models.CharField(max_length=1000, verbose_name='Barangay')),
                ('address_city', models.CharField(max_length=1000, verbose_name='City/Municipality')),
                ('address_province', models.CharField(max_length=1000, verbose_name='Province')),
                ('address_zip', models.CharField(max_length=4, verbose_name='Zip code')),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info_establishment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
