# Generated by Django 3.2.9 on 2021-11-06 05:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20211104_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female')], max_length=254, verbose_name='Sex')),
                ('phone', models.CharField(max_length=254, verbose_name='Phone number')),
                ('address_full', models.CharField(max_length=1000, verbose_name='Full address')),
                ('address_barangay', models.CharField(max_length=1000, verbose_name='Barangay')),
                ('address_city', models.CharField(max_length=1000, verbose_name='City/Municipality')),
                ('address_province', models.CharField(max_length=1000, verbose_name='Province')),
                ('address_zip', models.CharField(max_length=4, verbose_name='Zip code')),
                ('government_id', models.FileField(upload_to='people_id/', verbose_name='Photo of government-issued ID')),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VaccineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('', ''), ('Moderna', 'Moderna'), ('Novarax', 'Novarax'), ('Oxford AstraZeneca', 'Oxford AstraZeneca'), ('Pfizer-BioNTech', 'Pfizer-BioNTech'), ('Sinopharm', 'Sinopharm'), ('Sinovac', 'Sinovac'), ('Sputnik V', 'Sputnik V')], max_length=254, verbose_name='Brand')),
                ('first_dose_date', models.DateField(verbose_name='Date of 1st dose')),
                ('second_dose_date', models.DateField(blank=True, null=True, verbose_name='Date of 2nd dose')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='Status')),
                ('vaccine_card_id', models.FileField(upload_to='vaccine_id/', verbose_name='Photo of vaccine card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 5, 11, 2, 161780, tzinfo=utc), verbose_name='Termination date'),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='vaccinemodel',
            name='personal_info',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_info', to='mainapp.genericmodelmain', verbose_name='Personal Identifier'),
        ),
    ]
