# Generated by Django 3.2.9 on 2021-11-06 05:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211106_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplemodel',
            name='role',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 5, 28, 42, 184948, tzinfo=utc), verbose_name='Termination date'),
        ),
    ]
