# Generated by Django 3.2.9 on 2021-11-06 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211106_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 7, 51, 16, 578198, tzinfo=utc), verbose_name='Termination date'),
        ),
        migrations.AlterField(
            model_name='tracingmodel',
            name='establishment',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='tracingmodel',
            name='user_info',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
