# Generated by Django 3.2.9 on 2021-11-06 08:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_auto_20211106_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 8, 9, 58, 311859, tzinfo=utc), verbose_name='Termination date'),
        ),
        migrations.CreateModel(
            name='HealthcareModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name of healthcare organization')),
                ('address_full', models.CharField(max_length=1000, verbose_name='Full address')),
                ('address_barangay', models.CharField(max_length=1000, verbose_name='Barangay')),
                ('address_city', models.CharField(max_length=1000, verbose_name='City/Municipality')),
                ('address_province', models.CharField(max_length=1000, verbose_name='Province')),
                ('address_zip', models.CharField(max_length=4, verbose_name='Zip code')),
                ('user_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_info_healthcare', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
