# Generated by Django 3.2.9 on 2021-11-06 08:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211106_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 8, 10, 18, 491234, tzinfo=utc), verbose_name='Termination date'),
        ),
    ]
