# Generated by Django 3.2.9 on 2021-11-06 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_genericmodelmain_termination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodelmain',
            name='termination_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 5, 8, 30, 51, 831667, tzinfo=utc), verbose_name='Termination date'),
        ),
    ]
